baseURL = 'https://www.chengke.wang/'
DefaultContentLanguage = "en" # en, zh, zh-hant
languageCode = 'en-us'
title = 'Chengke'
theme = 'diary'

[params]
subtitle = '隻言片語・於此匯聚'

# JS errors occur if we disable the dark mode feature.
# disableDarkMode = true

[[menu.main]]
url = "/about"
name = "About Me"
weight = 1

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 2

[[menu.main]]
url = "/friends"
name = "Friends"
weight = 3

[[menu.main]]
# RSS Feed only generate the very lastest 10 posts. (You can edit
# /index.rss.xml by yourself to change this limit.)
url = "/index.xml"
name = "RSS"
weight = 4

